version: '3.3'

services:

  #backend
  airbnb-reviews:
    restart: always
    container_name: backend
    build: ./
    working_dir: /usr/src/airbnb_reviews
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/airbnb_review
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
 #     - ./wait-for-it.sh:/user/src/airbnb_review/wait-for-it.sh
    depends_on:
      - db
    links:
      - db
    #command: ["wait-for-it.sh","db:3306","--timeout=20","--",""]
    #command: ./wait-for-it.sh db:3306 -- sh -c "npm run seed && exec node server/server.js"
    command: bash -c "wait-for-it.sh db:3306 && npm run docker --timeout=20"


  #mysql

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: airbnb
    #command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
      - ./MYSQL/schema.sql:/docker-entrypoint-initdb.d/schema.sql
     # - /etc/mysql/my.cnf:/etc/mysql/my.cnf

volumes:
  db: