
version: 2
jobs:
   build:
     docker:
       - image: circleci/node:10.20.1
     steps:
       - checkout
       - run: npm install
       - run: CI=true npm run react
   test:
     docker:
       - image: circleci/node:10.20.1
     steps:
       - checkout
       - run: npm install
       - run: npm run test
     environment:
       MYSQL_PASSWORD: $MYSQL_PASSWORD
workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - test:
          requires:
            - build